//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikV1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kayitlar
    {
        public int Id { get; set; }
        public string AdiSoyadi { get; set; }
        public string Telefon { get; set; }
        public string İletisim { get; set; }
        public string CihazTuru { get; set; }
        public string Ariza { get; set; }
        public string Aksesuar { get; set; }
        public string Durum { get; set; }
        public string Aktif { get; set; }
        public string Not { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    }
}
