//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikV1._0
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database1Entities : DbContext
    {
        public Database1Entities()
            : base("name=Database1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Hizmetler> Hizmetler { get; set; }
        public virtual DbSet<Grafik> Grafik { get; set; }
        public virtual DbSet<KayitDurumu> KayitDurumu { get; set; }
        public virtual DbSet<Aksesuar> Aksesuar { get; set; }
        public virtual DbSet<Cihazlar> Cihazlar { get; set; }
        public virtual DbSet<Musteri> Musteri { get; set; }
        public virtual DbSet<Not> Not { get; set; }
        public virtual DbSet<Kayitlar> Kayitlar { get; set; }
        public virtual DbSet<StoklarTb> StoklarTb { get; set; }
    }
}
