//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikV1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteri
    {
        public int Id { get; set; }
        public string Unvan { get; set; }
        public string Adi { get; set; }
        public string Cep { get; set; }
        public string Tel { get; set; }
        public string Adres { get; set; }
        public string Email { get; set; }
        public string Not { get; set; }
    }
}
