//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikV1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoklarTb
    {
        public int Id { get; set; }
        public string Barkodu { get; set; }
        public string StokKodu { get; set; }
        public string StokAdi { get; set; }
        public string Birim { get; set; }
        public Nullable<int> Miktar { get; set; }
        public Nullable<int> Kalan { get; set; }
        public string Detay { get; set; }
    }
}
